CREATE TABLE Jobs
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	fixer NVARCHAR(50) NOT NULL,
	title NVARCHAR(50) NOT NULL,
	description NVARCHAR(500) NOT NULL,
	henchmenCount INT NOT NULL,
	reward INT NOT NULL,
	isAvailable TINYINT NOT NULL DEFAULT 1
)
